services:
  traefik:
    image: traefik:v2.9
    extra_hosts:
      - localhost:host-gateway
    container_name: traefik
    volumes:
      - ./traefik.yaml:/etc/traefik/config.yml:ro
    command:
      - "--api.dashboard=false"
      - "--providers.file.filename=/etc/traefik/config.yml"
      - "--entryPoints.http.address=:80"
    ports:
      - 80:80

  backend:
    image: gradle:7-jdk17
    extra_hosts:
      - localhost:host-gateway
    container_name: backend
    volumes:
      - ./:/app
      - gradle-cache:/root/.gradle/caches
    working_dir: /app
    environment:
      - SPRING_PROFILES_ACTIVE=local,compose
      - GH_PACKAGES_REPOSITORY_USER=${GH_PACKAGES_REPOSITORY_USER}
      - GH_PACKAGES_REPOSITORY_TOKEN=${GH_PACKAGES_REPOSITORY_TOKEN}
      - OAUTH2_CLIENT_ISSUER=${OAUTH2_CLIENT_ISSUER}
      - OAUTH2_CLIENT_ID=${OAUTH2_CLIENT_ID}
      - OAUTH2_CLIENT_SECRET=${OAUTH2_CLIENT_SECRET}
      - JAVA_OPTS=-XX:MaxDirectMemorySize=100M
    command: sh run.sh _start
    depends_on:
      - traefik
      - db
      - redis
    ports:
      - 8080:8080

  frontend:
    image: neuris/frontend
    extra_hosts:
      - localhost:host-gateway
    container_name: frontend
    volumes:
      - ./frontend/src/:/usr/src/app/src
    environment:
      - BACKEND_HOST=http://127.0.0.1
    command: npm run dev -- --host
    depends_on:
      - traefik
    ports:
      - 3000:3000

  db:
    image: postgres:12-alpine
    extra_hosts:
      - localhost:host-gateway
    restart: always
    container_name: db
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=neuris
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
    ports:
      - 5432:5432

  redis:
    image: cgr.dev/chainguard/redis:7.0
    extra_hosts:
      - localhost:host-gateway
    container_name: redis
    command:
      - "--maxmemory 256mb"
      - "--maxmemory-policy allkeys-lru"
      - "--timeout 300"
      - "--tcp-keepalive 10"
      - "--user redis on +@all -CONFIG ~* >password"
      - "--user default off resetchannels -@all"
    ports:
      - "6379:6379"

volumes:
  db-data:
  gradle-cache:
