openapi: 3.0.0
info:
  version: 0.0.1
  title: NeuRIS Normen Service API
  description: Interface for the normen service of the legal information system
  license:
    name: MIT
    url: https://mit-license.org

servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/VICTORDELCAMPO_1/neu-ris_normen_service_api_new/0.0.1
  - url: https://ris.prod.ds4g.net/api/norms
    description: Public production server
  - url: http://localhost:3000
    description: Local development server

paths:
  /norms:
    get:
      summary: Get a list of all available norms
      operationId: listNorms
      responses:
        "200":
          description: Successful response with list of all norms
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        guid:
                          $ref: "#/components/schemas/Guid"
                        longTitle:
                          type: string
                example:
                  data:
                    - guid: "86ee3aa7-b8ec-4f32-a6c7-2c7e13fc7919"
                      longTitle: "Gesetz über die Beschaffung sauberer Straßenfahrzeuge"
                    - guid: "07eb4f72-79cb-4070-93b5-62bfb44d3753"
                      longTitle: "Übereinkommen über das umweltgerechte Recycling von Schiffen"
        "400":
          description: ""

    post:
      summary: Create new norm
      operationId: createNorm
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NormWithoutGuid"
      responses:
        "201":
          description: Norm got successfully created
          headers:
            Location:
              description: URI reference for the new norm
              schema:
                type: string
        "400":
          description: Invalid norm

  /norms/{guid}:
    get:
      summary: Obtain a single norm by its Guid
      operationId: loadNorm
      parameters:
        - name: guid
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/Guid"
      responses:
        "200":
          description: Norm was found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Norm"
        "404":
          description: No norm found for this Guid

    patch:
      summary: Edit the frame data of a norm
      operationId: editNormFrame
      parameters:
        - name: guid
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/Guid"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                longTitle:
                  type: string
                officialShortTitle:
                  type: string
                officialAbbreviation:
                  type: string
                referenceNumber:
                  type: string
                publicationDate:
                  $ref: "#/components/schemas/Date"
                announcementDate:
                  $ref: "#/components/schemas/Date"
                citationDate:
                  $ref: "#/components/schemas/Date"
                frameKeywords:
                  type: string
                authorEntity:
                  type: string
                authorDecidingBody:
                  type: string
                authorIsResolutionMajority:
                  type: boolean
                leadJurisdiction:
                  type: string
                leadUnit:
                  type: string
                participationType:
                  type: string
                participationInstitution:
                  type: string
                documentTypeName:
                  type: string
                documentNormCategory:
                  type: string
                documentTemplateName:
                  type: string
                subjectFna:
                  type: string
                subjectPreviousFna:
                  type: string
                subjectGesta:
                  type: string
                subjectBgb3:
                  type: string
      responses:
        "204":
          description: Norm was updated

        "400":
          description: ""

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

  schemas:
    Guid:
      description: The globally unique identifier of the norm (format in UUID)
      type: string
      format: uuid

    Date:
      description: The date format in XML files
      type: string
      pattern: '^[1-2]\d{3}-[0-1]\d-[0-3]\d$'

    ParagraphWithoutGuid:
      type: object
      required:
        - marker
        - text
      properties:
        marker:
          type: string
        text:
          type: string
      example:
        marker: "(1)"
        text: "Dieses Gesetz regelt Mindestziele und deren Sicherstellung bei der Beschaffung bestimmter Straßenfahrzeuge und Dienstleistungen, für die diese Straßenfahrzeuge eingesetzt werden, durch öffentliche Auftraggeber und Sektorenauftraggeber."

    ArticleWithoutGuid:
      type: object
      required:
        - marker
        - paragraphs
      properties:
        marker:
          type: string
        title:
          type: string
        paragraphs:
          type: array
          items:
            $ref: "#/components/schemas/ParagraphWithoutGuid"
      example:
        marker: "§ 1"
        title: "Allgemeiner Anwendungsbereich"
        paragraphs:
          - marker: "(1)"
            text: "Dieses Gesetz regelt Mindestziele und deren Sicherstellung bei der Beschaffung bestimmter Straßenfahrzeuge und Dienstleistungen, für die diese Straßenfahrzeuge eingesetzt werden, durch öffentliche Auftraggeber und Sektorenauftraggeber."

    NormWithoutGuid:
      type: object
      required:
        - longTitle
        - articles
      properties:
        longTitle:
          type: string
        officialShortTitle:
          type: string
        officialAbbreviation:
          type: string
        referenceNumber:
          type: string
        publicationDate:
          $ref: "#/components/schemas/Date"
        announcementDate:
          $ref: "#/components/schemas/Date"
        citationDate:
          $ref: "#/components/schemas/Date"
        frameKeywords:
          type: string
        authorEntity:
          type: string
        authorDecidingBody:
          type: string
        authorIsResolutionMajority:
          type: boolean
        leadJurisdiction:
          type: string
        leadUnit:
          type: string
        participationType:
          type: string
        participationInstitution:
          type: string
        documentTypeName:
          type: string
        documentNormCategory:
          type: string
        documentTemplateName:
          type: string
        subjectFna:
          type: string
        subjectPreviousFna:
          type: string
        subjectGesta:
          type: string
        subjectBgb3:
          type: string
        articles:
          type: array
          items:
            $ref: "#/components/schemas/ArticleWithoutGuid"
      example:
        longTitle: "Gesetz über die Beschaffung sauberer Straßenfahrzeuge"
        officialShortTitle: "Notenwechsel vom 25. September 1990 zum NATO-Truppenstatut"
        officialAbbreviation: "2. KostRMoG"
        referenceNumber: "1 BvR 2011/94"
        publicationDate: "2022-03-30"
        announcementDate: "2012-03-30"
        citationDate: "2002-03-30"
        frameKeywords: "BGBl I 2009, Nr 027"
        authorEntity: "DEU"
        authorDecidingBody: "BMinI"
        authorIsResolutionMajority: true
        leadJurisdiction: "BMELV"
        leadUnit: "BMELV 335"
        participationType: "EZ"
        participationInstitution: "BR"
        documentTypeName: "RV"
        documentNormCategory: "NS"
        documentTemplateName: "ASD"
        subjectFna: "6/32"
        subjectPreviousFna: "6/31"
        subjectGesta: "Sample Text"
        subjectBgb3: "Sample Text"
        articles:
          - marker: "§ 1"
            title: "Allgemeiner Anwendungsbereich"
            paragraphs:
              - marker: "(1)"
                text: "Dieses Gesetz regelt Mindestziele und deren Sicherstellung bei der Beschaffung bestimmter Straßenfahrzeuge und Dienstleistungen, für die diese Straßenfahrzeuge eingesetzt werden, durch öffentliche Auftraggeber und Sektorenauftraggeber."

    Paragraph:
      allOf:
        - $ref: "#/components/schemas/ParagraphWithoutGuid"
        - type: object
          required:
            - guid
          properties:
            guid:
              $ref: "#/components/schemas/Guid"
          example:
            guid: "eb6f27c7-79ef-4b25-8aef-b8726f6ed26f"
            marker: "(1)"
            text: "Dieses Gesetz regelt Mindestziele und deren Sicherstellung bei der Beschaffung bestimmter Straßenfahrzeuge und Dienstleistungen, für die diese Straßenfahrzeuge eingesetzt werden, durch öffentliche Auftraggeber und Sektorenauftraggeber."

    Article:
      type: object
      required:
        - guid
        - marker
        - paragraphs
      properties:
        guid:
          $ref: "#/components/schemas/Guid"
        title:
          type: string
        marker:
          type: string
        paragraphs:
          type: array
          items:
            $ref: "#/components/schemas/Paragraph"
      example:
        guid: "07eb4f72-79cb-4070-93b5-62bfb44d3753"
        marker: "§ 1"
        title: "Allgemeiner Anwendungsbereich"
        paragraphs:
          - guid: "eb6f27c7-79ef-4b25-8aef-b8726f6ed26f"
            marker: "(1)"
            text: "Dieses Gesetz regelt Mindestziele und deren Sicherstellung bei der Beschaffung bestimmter Straßenfahrzeuge und Dienstleistungen, für die diese Straßenfahrzeuge eingesetzt werden, durch öffentliche Auftraggeber und Sektorenauftraggeber."

    Norm:
      allOf:
        - $ref: "#/components/schemas/NormWithoutGuid"
        - type: object
          required:
            - guid
          properties:
            guid:
              $ref: "#/components/schemas/Guid"
          example:
            guid: "86ee3aa7-b8ec-4f32-a6c7-2c7e13fc7919"

security:
  - BasicAuth: []
