openapi: 3.0.0
info:
  version: 0.0.1
  title: NeuRIS Normen Service API
  description: Interface for the normen service of the legal information system
  license:
    name: MIT
    url: https://mit-license.org

servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/VICTORDELCAMPO_1/neu-ris_normen_service_api/0.0.1
  - url: https://ris.prod.ds4g.net/api/norms
    description: Public production server
  - url: http://localhost:3000
    description: Local development server

paths:
  /norms:
    get:
      summary: Get a list of all available norms
      operationId: listNorms
      responses:
        "200":
          description: Successful response with list of all norms
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        guid:
                          $ref: "#/components/schemas/Guid"
                        officialLongTitle:
                          type: string
                example:
                  - guid: "86ee3aa7-b8ec-4f32-a6c7-2c7e13fc7919"
                    officialLongTitle: "Gesetz über die Beschaffung sauberer Straßenfahrzeuge"
                  - guid: "07eb4f72-79cb-4070-93b5-62bfb44d3753"
                    officialLongTitle: "Übereinkommen über das umweltgerechte Recycling von Schiffen"
        "400":
          description: ""

    post:
      summary: Import data to create a new norm
      operationId: importNorm
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ImportableNorm"
      responses:
        "201":
          description: Norm got successfully created
          headers:
            Location:
              description: URI reference for the new norm
              schema:
                type: string
        "400":
          description: Invalid norm

  /norms/{guid}:
    get:
      summary: Load a single norm
      operationId: loadNorm
      parameters:
        - name: guid
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/Guid"
      responses:
        "200":
          description: Norm was found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Norm"
        "404":
          description: No norm found for this query

    put:
      summary: Edit the frame data of a norm
      operationId: editNormFrame
      parameters:
        - name: guid
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/Guid"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NormFrame"
      responses:
        "204":
          description: Norm was updated
        "400":
          description: ""

  /norms/xml/{guid}:
    get:
      summary: Load a single as XML in LegalDocML format
      operationId: loadNormAsXML
      parameters:
        - name: guid
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/Guid"
      responses:
        "200":
          description: Norm was found
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/LegalDocML"

        "404":
          description: No norm found for this query

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

  schemas:
    Guid:
      description: The globally unique identifier of the norm (format in UUID)
      type: string
      format: uuid
      example: "6a18380f-5c65-4f4d-902d-d49694f25de2"

    Date:
      description: The date format in XML files
      type: string
      pattern: '^[1-2]\d{3}-[0-1]\d-[0-3]\d$'
      example: "2020-10-21"

    UndefinedDate:
      description: A field that takes one of three values
      type: string
      enum: [UNDEFINED_UNKNOWN, UNDEFINED_FUTURE, UNDEFINED_NOT_PRESENT]

    ParagraphWithoutGuid:
      type: object
      required:
        - text
      properties:
        marker:
          type: string
          example: "(1)"
        text:
          type: string
          example: "Dieses Gesetz regelt Mindestziele und deren Sicherstellung bei der Beschaffung bestimmter Straßenfahrzeuge und Dienstleistungen, für die diese Straßenfahrzeuge eingesetzt werden, durch öffentliche Auftraggeber und Sektorenauftraggeber."

    ArticleWithoutGuid:
      type: object
      required:
        - marker
        - paragraphs
      properties:
        marker:
          type: string
          example: "§ 1"
        title:
          type: string
          example: "Allgemeiner Anwendungsbereich"
        paragraphs:
          type: array
          items:
            $ref: "#/components/schemas/ParagraphWithoutGuid"

    ImportableNorm:
      allOf:
        - $ref: "#/components/schemas/ImportableNormFrame"
        - type: object
          required:
            - officialLongTitle
            - articles
          properties:
            articles:
              type: array
              items:
                $ref: "#/components/schemas/ArticleWithoutGuid"

    Paragraph:
      allOf:
        - $ref: "#/components/schemas/ParagraphWithoutGuid"
        - type: object
          required:
            - guid
          properties:
            guid:
              $ref: "#/components/schemas/Guid"

    Article:
      allOf:
        - $ref: "#/components/schemas/ArticleWithoutGuid"
        - type: object
          required:
            - guid
          properties:
            guid:
              $ref: "#/components/schemas/Guid"
            paragraphs:
              type: array
              items:
                $ref: "#/components/schemas/Paragraph"

    Norm:
      allOf:
        - $ref: "#/components/schemas/NormFrame"
        - type: object
          required:
            - guid
            - officialLongTitle
          properties:
            guid:
              $ref: "#/components/schemas/Guid"
            articles:
              type: array
              items:
                $ref: "#/components/schemas/Article"

    ImportableNormFrame:
      type: object
      properties:
        officialLongTitle:
          type: string
          example: "Gesetz über die Beschaffung sauberer Straßenfahrzeuge"
        officialShortTitle:
          type: string
          example: "Saubere-Fahrzeuge-Beschaffungs-Gesetz"
        officialAbbreviation:
          type: string
          example: "SaubFahrzeugBeschG"
        referenceNumber:
          type: string
          example: "1 BvR 2011/94"
        announcementDate:
          $ref: "#/components/schemas/Date"
        citationDate:
          $ref: "#/components/schemas/Date"
        frameKeywords:
          type: string
          example: "BGBl I 2021, Nr 031;geltendes Bundesrecht;Umsetzung EG-Recht;Umsetzung EURL 2019/1161;Beschaffung;sauber;Straßenfahrzeug"
        providerEntity:
          type: string
          example: "DEU"
        providerDecidingBody:
          type: string
          example: "BT"
        providerIsResolutionMajority:
          type: boolean
          example: true
        leadJurisdiction:
          type: string
          example: "BMVI"
        leadUnit:
          type: string
          example: "G 22"
        participationType:
          type: string
          example: "EZ"
        participationInstitution:
          type: string
          example: "BR"
        subjectFna:
          type: string
          example: "FNA 703-12"
        subjectGesta:
          type: string
          example: "GESTA J040"
        documentNumber:
          type: string
          example: ""
        documentCategory:
          type: string
          example: ""
        risAbbreviationInternationalLaw:
          type: string
          example: ""
        unofficialReference:
          type: string
          example: ""
        applicationScopeArea:
          type: string
          example: ""
        applicationScopeStartDate:
          $ref: "#/components/schemas/Date"
        applicationScopeEndDate:
          $ref: "#/components/schemas/Date"
        validityRule:
          type: string
          example: ""
        celexNumber:
          type: string
          example: ""
        definition:
          type: string
          example: ""
        categorizedReference:
          type: string
          example: ""
        otherFootnote:
          type: string
          example: "Das G wurde vom Bundestag beschlossen und ist am 1.1.1998 in Kraft getreten."
        expirationDate:
          $ref: "#/components/schemas/Date"
        entryIntoForceDate:
          $ref: "#/components/schemas/Date"
        unofficialLongTitle:
          type: string
          example: ""
        unofficialShortTitle:
          type: string
          example: "Nichtamtliche Kurzüberschrift"
        unofficialAbbreviation:
          type: string
          example: "Nichtamtliche Buchstabenabkürzung"
        risAbbreviation:
          type: string
          example: "SaubFahrzeugBeschG"
        printAnnouncementGazette:
          type: string
          example: ""
        printAnnouncementYear:
          type: string
          example: "1996"
        printAnnouncementPage:
          type: string
          example: "1102"
        documentStatusWorkNote:
          type: string
          example: ""
        documentStatusDescription:
          type: string
          example: ""
        documentStatusDate:
          $ref: "#/components/schemas/Date"
        statusNote:
          type: string
          example: ""
        statusDescription:
          type: string
          example: ""
        statusDate:
          $ref: "#/components/schemas/Date"
        statusReference:
          type: string
          example: ""
        repealNote:
          type: string
          example: ""
        repealArticle:
          type: string
          example: ""
        repealDate:
          $ref: "#/components/schemas/Date"
        repealReferences:
          type: string
          example: ""
        reissueNote:
          type: string
          example: ""
        reissueArticle:
          type: string
          example: ""
        reissueDate:
          $ref: "#/components/schemas/Date"
        reissueReference:
          type: string
          example: ""
        otherStatusNote:
          type: string
          example: ""
        text:
          type: string
          example: "text"
        ageOfMajorityIndication:
          type: string
          example: ""
        divergentExpirationDate:
          $ref: "#/components/schemas/Date"
        divergentExpirationDateState:
          $ref: "#/components/schemas/UndefinedDate"
        principleExpirationDate:
          $ref: "#/components/schemas/Date"
        principleExpirationDateState:
          $ref: "#/components/schemas/UndefinedDate"
        expirationNormCategory:
          type: string
          example: ""
        divergentEntryIntoForceDate:
          $ref: "#/components/schemas/Date"
        divergentEntryIntoForceDateState:
          $ref: "#/components/schemas/UndefinedDate"
        principleEntryIntoForceDate:
          $ref: "#/components/schemas/Date"
        principleEntryIntoForceDateState:
          $ref: "#/components/schemas/UndefinedDate"
        entryIntoForceNormCategory:
          type: string
          example: ""

    NormFrame:
      allOf:
        - $ref: "#/components/schemas/ImportableNormFrame"
        - type: object
          properties:
            publicationDate:
              $ref: "#/components/schemas/Date"
            documentTypeName:
              type: string
              example: "RV"
            documentNormCategory:
              type: string
              example: "XX"
            documentTemplateName:
              type: string
              example: "Template"
            subjectPreviousFna:
              type: string
              example: "FNA 703-11"
            subjectBgb3:
              type: string
              example: "BGB III 234"
            printAnnouncementGazette:
              type: string
              example: ""
            printAnnouncementYear:
              type: string
              example: ""
            printAnnouncementNumber:
              type: string
              example: ""
            printAnnouncementPage:
              type: string
              example: ""
            printAnnouncementInfo:
              type: string
              example: ""
            printAnnouncementExplanations:
              type: string
              example: ""
            digitalAnnouncementMedium:
              type: string
              example: ""
            digitalAnnouncementDate:
              $ref: "#/components/schemas/Date"
            digitalAnnouncementEdition:
              type: string
              example: ""
            digitalAnnouncementYear:
              type: string
              example: ""
            digitalAnnouncementPage:
              type: string
              example: ""
            digitalAnnouncementArea:
              type: string
              example: ""
            digitalAnnouncementAreaNumber:
              type: string
              example: ""
            digitalAnnouncementInfo:
              type: string
              example: ""
            digitalAnnouncementExplanations:
              type: string
              example: ""
            euAnnouncementGazette:
              type: string
              example: ""
            euAnnouncementYear:
              type: string
              example: ""
            euAnnouncementSeries:
              type: string
              example: ""
            euAnnouncementNumber:
              type: string
              example: ""
            euAnnouncementPage:
              type: string
              example: ""
            euAnnouncementInfo:
              type: string
              example: ""
            euAnnouncementExplanations:
              type: string
              example: ""
            otherOfficialAnnouncement:
              type: string
              example: ""
            statusNote:
              type: string
              example: ""
            statusDescription:
              type: string
              example: ""
            statusDate:
              $ref: "#/components/schemas/Date"
            statusReference:
              type: string
              example: ""
            repealNote:
              type: string
              example: ""
            repealArticle:
              type: string
              example: ""
            repealDate:
              $ref: "#/components/schemas/Date"
            repealReferences:
              type: string
              example: ""
            reissueNote:
              type: string
              example: ""
            reissueArticle:
              type: string
              example: ""
            reissueDate:
              $ref: "#/components/schemas/Date"
            reissueReference:
              type: string
              example: ""
            otherStatusNote:
              type: string
              example: ""
            documentStatusWorkNote:
              type: string
              example: ""
            documentStatusDescription:
              type: string
              example: ""
            documentStatusDate:
              $ref: "#/components/schemas/Date"
            documentStatusReference:
              type: string
              example: ""
            documentStatusEntryIntoForceDate:
              $ref: "#/components/schemas/Date"
            documentStatusProof:
              type: string
              example: ""
            documentTextProof:
              type: string
              example: ""
            otherDocumentNote:
              type: string
              example: ""
            ageIndicationStart:
              type: string
              example: ""
            ageIndicationEnd:
              type: string
              example: ""
            text:
              type: string
              example: ""
            europeanLegalIdentifier:
              type: string
              example: ""
            completeCitation:
              type: string
              example: ""
            divergentDocumentNumber:
              type: string
              example: ""
            digitalEvidenceLink:
              type: string
              example: ""
            digitalEvidenceRelatedData:
              type: string
              example: ""
            digitalEvidenceExternalDataNote:
              type: string
              example: ""
            digitalEvidenceAppendix:
              type: string
              example: ""
            ageOfMajorityIndication:
              type: string
              example: ""
            divergentExpirationDate:
              $ref: "#/components/schemas/Date"
            divergentExpirationDateState:
              type: string
              example: ""
            principleExpirationDate:
              $ref: "#/components/schemas/Date"
            isExpirationDateTemp:
              type: boolean
              example: false
            principleExpirationDateState:
              type: string
              example: ""
            expirationDateState:
              type: string
              example: ""
            expirationNormCategory:
              type: string
              example: ""
            divergentEntryIntoForceDate:
              $ref: "#/components/schemas/Date"
            principleEntryIntoForceDate:
              $ref: "#/components/schemas/Date"
            principleEntryIntoForceDateState:
              type: string
              example: ""
            entryIntoForceDateState:
              type: string
              example: ""
            entryIntoForceNormCategory:
              type: string
              example: ""

    LegalDocML:
      type: object
      xml:
        name: akomaNtoso
        namespace: http://Inhaltsdaten.LegalDocML.de/1.4
        prefix: akn

security:
  - BasicAuth: []
