# Allows to run standalone Playwright based E2E/A11Y tests in particular browser,
# for debugging...
name: Manual Playwright test

on:
  workflow_dispatch:
    inputs:
      browser:
        description: "Playwright browser engine"
        required: true
        type: choice
        options:
          - chromium
          - firefox
      mode:
        description: "Type of tests"
        required: true
        type: choice
        options:
          - e2e
          - a11y
      runs:
        description: "Number of subsequent runs"
        required: false
        type: string
        default: "1"
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '00 6 * * *'

jobs:
  playwright-test:
    uses: ./.github/workflows/_playwright-test.yml
    with:
      browser: ${{ inputs.browser }}
      mode: ${{ inputs.mode }}
      runs: ${{ inputs.runs }}
    secrets: inherit
