# Allows to run standalone Playwright based E2E/A11Y tests in particular browser,
# for debugging...
name: Manual Playwright test

on:
  workflow_dispatch:
    inputs:
      browser:
        description: "Playwright browser engine"
        required: true
        type: choice
        options:
          - chromium
          - firefox

jobs:
  playwright-test:
    uses: ./.github/workflows/playwright-test.yml
    with:
      browser: ${{ inputs.browser }}
    secrets: inherit
